### ISSUE TITLE
open procure: expired central tender displayed as open 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#100]
http://next.obudget.org/i/tenders/central/600875/technology-11-2017?li=1&theme=govbuy:

see the ending date (23.1.18) and status (`פתוח`)
![image](https://user-images.githubusercontent.com/3581741/43709545-cd019d7c-9975-11e8-8e6b-58d213ee6aa4.png)

checking the data source shows the status there was changed:

1. https://www.mr.gov.il/CentralTenders/technology/Pages/11-2017.aspx:
(פורסם וממתין לתוצאות)
![image](https://user-images.githubusercontent.com/3581741/43709625-fb643ed6-9975-11e8-8af5-77a291808a69.png)

2. https://www.mr.gov.il/officestenders/Pages/officetender.aspx?pID=600875:
(הסתיים)
![image](https://user-images.githubusercontent.com/3581741/43709653-0d1567e0-9976-11e8-819b-2dd1c93e5b0b.png)

I would suggest changing into `הסתיים` if any of the relevant screens statuses (original publication or the relevant documents) was set as expired.

**Comment by akariv** [comment]
???

we already discussed this - the lookup table mapped 'פורסם וממתין לתוצאות' to 'פתוח'.
once you've fixed that, it should resolve to the correct status.

**Comment by akariv** [comment]
Duplicate of OpenBudget/budgetkey-app-search#124
