### ISSUE TITLE
Allow creating links in the datatable

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-app-generic-item#13]
Define a method for specifying that a certain header should be a link.
Links should be displayed as an icon, not with the full url.

**Comment by simonbor** [comment]
In the other words you want add Hyper Link ability to column headers?
![image](https://user-images.githubusercontent.com/8211293/34123790-69de58e4-e439-11e7-9ae3-f18fa3bd9c6f.png)

**Comment by akariv** [comment]
No - I want that certain cells in the table would be links (e.g. if have a
name of an organisation returned, I want it to link to the organisation
page).
