### ISSUE TITLE
Allow specifying formatting for number columns

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-app-generic-item#14]
Columns containing currency should be formatted with ',' separators and decimal points, and have ₪ at the end.
(This should not apply to _all_ numbers, as some might be non currency - e.g. years)

**Comment by kravets-levko** [comment]
@akariv I think this issue and #13 are very similar - both of them are about value formatting (as I understand). I think, we can add one more mapping to descriptors - to specify formats for specific columns, and use that map when rendering data table. WDYT?

**Comment by akariv** [comment]
Yes, sounds good.

**Comment by simonbor** [comment]
Is it worth making it configurable? 
For example let ability changing the "," to "." and/or the ₪ to $

**Comment by akariv** [comment]
Perhaps semi-configurable - have a list of predefined formatters and allow
configuration to map a column to a formatter

**Comment by simonbor** [comment]
I hesitate between these - 
`Intl.NumberFormat().format(x)`
and
`parseFloat(x).toLocaleString('en-IN')`

**Comment by akariv** [comment]
@simonbor this issue is more about the mechanism of assigning these custom formatters to headers, and less about the actual formatters.
