### ISSUE TITLE
Implement data-questions for support

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-app-generic-item#18]
Add a descriptors/supports/questions.json which implements the following questions:

- [ ] סך התמיכות שיצאו מהתקנה הזו לנמען של התמיכה בשנים אחרות (מסודרות לפי שנה) ששולמו/אושרו בשנה כלשהי/כלל השנים
- [ ] כלל התמיכות שיצאו מהתקנה הזו (מסודרות לפי שנה ונמען) ששולמו/אושרו בשנה כלשהי/כלל השנים
- [ ] סך התמיכות שיצאו מהתקנה הזו (מסודרות לפי שנה) ששולמו/אושרו בשנה כלשהי/כלל השנים
- [x] כלל התמיכות שהנמען של התמיכה קיבל (מסודרות לפי שנה ותקנה תקציבית) ששולמו/אושרו בשנה כלשהי/כלל השנים
- [ ] תקנות נוספות מהן הנמען של התמיכה קיבל תמיכות, לפי סה״כ כספים ששולמו/אושרו בשנה כלשהי/כלל השנים
- [ ] סך התמיכות שהארגון קיבל (מסודרות לפי שנה ותקנה תקציבית) לפי סה״כ כספים ששולמו/אושרו בשנה כלשהי/כלל השנים

**Comment by akariv** [comment]
http://data.obudget.org/
data source: obudget-next
data table: raw_supports

@danielbraun

**Comment by danielbraun** [comment]
Has it been implemented in https://github.com/OpenBudget/budgetkey-app-generic-item/commit/96acf8ec387fb68254cd95ce4162496b3d23b5dd#diff-0d2febe02b6c80d8f065f51b49c82406 ?

**Comment by akariv** [comment]
@danielbraun only
כלל התמיכות שהנמען של התמיכה קיבל (מסודרות לפי שנה ותקנה תקציבית) ששולמו/אושרו בשנה כלשהי/כלל השנים
was implemented.
The rest is still missing (added checkboxes to illustrate that)
