### ISSUE TITLE
Data table - visual improvements

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-app-generic-item#25]
- [x] add loader while results are loading
- [x] add indication when no results were received
- [x] add indication when an error occurred

**Comment by akariv** [comment]
Sample page:
http://next.obudget.org/i/org/association/580294072

**Comment by simonbor** [comment]
Where I can see the example of the loader?

**Comment by akariv** [comment]
In the search page:
next.obudget.org/app/search/
