### ISSUE TITLE
affix on item page

### ISSUE THREAD

**Issue by mushon** [OpenBudget/budgetkey-app-generic-item#30]
on page load all is viewable:
![image](https://user-images.githubusercontent.com/27123/32749663-aa5d0c08-c8c8-11e7-9a7f-9790c412de5c.png)

when we scroll the page down the site header should stay fixed:
![image](https://user-images.githubusercontent.com/27123/32749682-b91f9878-c8c8-11e7-874b-b35b0dc832c8.png)

until the item title pushes them out:
![image](https://user-images.githubusercontent.com/27123/32749706-ca60d5de-c8c8-11e7-9c17-f8893e49e920.png)

and replaces them as the fixed header:
![image](https://user-images.githubusercontent.com/27123/32749770-08b236e8-c8c9-11e7-9b90-200db28d27e4.png)

On scroll up the site header should appear immediately (revealing the search):
![image](https://user-images.githubusercontent.com/27123/32749706-ca60d5de-c8c8-11e7-9c17-f8893e49e920.png)

**Comment by akariv** [comment]
not doing this atm (maybe when new design comes in)
