### ISSUE TITLE
item page header should use ng2-components header

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-app-generic-item#43]
in [this PR](https://github.com/OpenBudget/budgetkey-ng2-components/pull/11) a search bar was added to the ng2-components header, need to integrate the latest ng2-components, enable the search bar in the header and fix the design of the search bar in ng2-components (functionality works)

**Comment by akariv** [comment]
Fixed via https://github.com/OpenBudget/budgetkey-app-generic-item/commit/93de89fa35268dc90b387da82abb050dad5aea0b
