### ISSUE TITLE
Create a Office Tender Page for open (new/updated) tenders

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#47]
(Invisoin link: https://projects.invisionapp.com/d/main#/console/7587193/276178413/preview )

![image](https://user-images.githubusercontent.com/3581741/36353973-33ed64aa-14d6-11e8-80c9-d48f156a1fd3.png)

Open Office Tender (`WHERE tender_type = 'office' AND decision='חדש') OR (decision='עודכן'))

dynamic values:
-------------

|No. | data source | label | value / logic | comments |
|---|---|---|---|---|
1 | any of the fields |none| if a value changed during  `TODAY <= LAST_UPDATE_DATE + 7 days`value should be `עודכן!`, if `TODAY <= START_DATE + 7 ` value should be `חדש!` |  do not use the `decision` field value here, as it is not reflecting what we intend to show with this label. | Don't use the raw value of the `decision` field, as it does not consist the required logic! |
2 | `decision` | none | `מכרז פתוח`: based on the  `decision` field: if `decision` == `חדש` or `decision` == `עודכן`. |  other values to be handled in #56 #57| 
3 | `LAST_UPDATE_DATE` | `עדכון אחרון` | date | dd.mm.yyyy |
4 | `START_DATE` | `פרסום ראשון` | date | dd.mm.yyyy |
5 | `DESCRIPTION` | | | BOLD |
6 | `decision` | none | `מכרז פתוח`: based on the  `decision` field: if `decision` == `חדש` or `decision` == `עודכן`. | For now, when the `descision` field consists other value, show nothing, To Be Continued| 
7 | `PUBLISHER` | none | | in the future it should be clickable and lead to a publisher entity page, currently simple text | 
8 | `quarterly_contract_spending_reports.supplier_name` | none | A. if the `tender_id` appears in `quarterly_contract_spending_reports.manof_ref` and `count('supplier_name') == 1`, display `supplier_name`). B. if `count('supplier_name') > 2, display `[num] ספקים`.  C. Otherwise, leave empty | 
9a | `quarterly_contract_spending_reports.executed`, `quarterly_contract_spending_reports.volume`| | pie chart || 
9b | `quarterly_contract_spending_reports.executed`, `quarterly_contract_spending_reports.volume` | 'עד כה בוצעו...% מתוך:` | `exectued` / `volume` | dd% (round result). Notice this formula should relate to ALL relevant suppliers (using `manof_ref`) |
9c | `quarterly_contract_spending_reports.executed` | none | sum of all `exectued` values for the relevant `manof_ref` | add NIS symbol to value|
10 | `SUBJECTS` | | label per each value. Each label should be linked to a search results page of procurement_tenders from the same topic | 
11a | `tender_id`| מספר מנו"ף | `tender_id` | |
11b | `tender_type` | סוג המכרז: | if `tender_type` == `office` -->  `משרדי` | |
11c | `CLAIM_DATE` | מועד סגירה: ... בשעה... | | dd.mm.yyyy + HH:MM: | 
11d| `CONTACT` | אנשי קשר: | | email adresses should be clickable and open user's email client|
12a | actionable A # | | | to be handled on a follow #51 |
12b | actionable B # | | | to be handled on a follow #51 |
13 | (table intro) | table headers : `הזוכים במכרז`, ` סכום ההתקשרות`, `עד כה שולם` | values in this block are to be calculated by the intersection between current `tender_id` and ``quarterly_contract_spending_reports.manof_ref`. Table should be sorted by the `value` amount (13b) in a decreasing order (biggest value, first row) | 
13a | `quarterly_contract_spending_reports.supplier_name` | | | in the future it would be linked to future entity page, currently nothing special | 
13b | `quarterly_contract_spending_reports.volume`| none, add a NIS symbol | sum of `quarterly_contract_spending_reports.volume` of the concrete supllier under the concrete `manof_ref` | don't round result, display real number (up to 2 digits after demical point)  | 
13c | `quarterly_c`quarterly_contract_spending_reports.executed`| none, add a NIS symbol | sum of `quarterly_contract_spending_reports.executed` of the concrete supllier under the concrete `manof_ref` | don't round result, display real number (up to 2 digits after demical point) | 
13d | | link to the relevant התקשרות page| | 
14 | (table intro) | table shows chronological history of the tender, in a reversed order. Two type of updates to be included: tender status change (bolded), payment (taken from the quarterly report) (bolded row), uploading/updating file (normal text for the entrie row) | |
14a |`quarterly_c`quarterly_contract_spending_reports.volume`, `quarterly_c`quarterly_contract_spending_reports.executed` | no headers | pie chart of the `executed` out of the total `volume` | the pie chart refers to the tender's total exectued out of the total approved values, not to be confused with 13 above  | 
14b | (update date -- from either  `quarterly_c`quarterly_contract_spending_reports` or `procurement_tenders` | | if date == Today -->  `היום`, if Today - date <= 7 --> `ימים x לפני`, if Today- date < 4 weeks, divide days number by 7 -->  `לפני כ-x שבועות`, otherwise: raw date (DD.MM.YYYY) | |
14c | `quarterly_contract_spending_report.PAGE_URL` or `quarterly_contract_spending_reports.REPORT-URL`| don't show address, just display the icon with a relevant link | | to be opened in a new tab|
14d | update message | | |needs to set logic to be handled in a separate issue, to be hanled in #52 | 
15 | grid intro, based on `procurement_tenders.DOCUMENTS` | `קבצים מצורפים` | | |
15a | `update_time` | none | (update date -- from either `quarterly_contract_spending_reports` or `procurement_tenders`) if date == Today -->  `היום`, if Today - date <= 7 --> `ימים x לפני`, if Today- date < 4 weeks, divide days number by 7 -->  `לפני כ-x שבועות`, otherwise: raw date (DD.MM.YYYY) ||
15b | icon + file name |  | icon to be set by the file type extention (doc/pdf/xls/csv), each element should be linked to the `link` address. If the number of elements is bigger than 3, start a new row of elements |

**Comment by akariv** [comment]
publisher entity page --> didn't we say that we're not going to have those?

**Comment by noamoss** [comment]
@akariv 

>publisher entity page --> didn't we say that we're not going to have those?

we did, forgot to add a comment, fixed. see description.

**Comment by noamoss** [comment]
(notice I updated the defining criteria of this issue's description, to be more explicit and prevent future duplications The current criteria:

FROM procurement_tenders
WHERE tender_type = 'office'
  AND (decision='בוטל' or decision='עודכן')
