### ISSUE TITLE
Add Actionables by scenario for center+office tenders

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#51]
For some predefined scenarios of the process (i.e. procurement_tenders+quarterly spending, we should display user possible actions they can take in the real world. Notice the static text should consist also dynamic (relevant) links for the specific entities. 

![image](https://user-images.githubusercontent.com/3581741/36349380-309badfe-148e-11e8-9b01-71332959cbc8.png)

We should enable up to two actionable recommendations (A and B).

This issue is to define the data structure for the new mechanism, in a way that will enable us to use it also on other spots in the OpenBudget Project (i.e. not only on tenders).

**Comment by akariv** [comment]
What dictates the recommendations?
Is it just static text (such as recommendation A)? 
Does it depend on the state of the record or other data within in?
Recommendation B contains a "similar items" list - we don't have such functionality and not planning to add one atm.

**Comment by noamoss** [comment]
>What dictates the recommendations?

combination of parameters (we don't have the full list of scenarios yet, that's why I prefer to discuss before writing them).

>Is it just static text (such as recommendation A)?

yes.

>Does it depend on the state of the record or other data within in?

both, and also might be affected by the status in another record (i.e. a combination of quarterly report and tender record)

>Recommendation B contains a "similar items" list - we don't have such functionality and not planning to add one atm.

ok

**Comment by noamoss** [comment]
https://docs.google.com/spreadsheets/d/1JkZooBwoxKPlrXWWwUtNHLMdxc-iG0n5tdGZ23I8fYY/edit#gid=1250185114

**Comment by noamoss** [comment]
checked and approved on live.
