### ISSUE TITLE
Cancelled Office Tender

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#56]
follow-up of #47 

..
Defining critera:
```
FROM procurement_tenders
WHERE tender_type = 'office'  AND decision='בוטל'
```

(Invisoin link: https://projects.invisionapp.com/d/main#/console/7587193/276178413/preview )

![image](https://user-images.githubusercontent.com/3581741/36353973-33ed64aa-14d6-11e8-80c9-d48f156a1fd3.png)

Open Office Tender (WHERE tender_type = 'office' AND (decision='חדש'` or decision='עודכן') dynamic values:
-------------

|No. | data source | label | value / logic | comments |
|---|---|---|---|---|
1 | `LAST_UPDATE_DATE` + `DECISION` |  none | if the update date of the decision into 'בוטל'  was during the last 7 dates, show label| otherwise don't show anything in the block|
2 | `decision` | none | `מכרז שבוטל` | 
3 | `LAST_UPDATE_DATE` | `עדכון אחרון` | date | dd.mm.yyyy |
4 | `START_DATE` | `פרסום ראשון` | date | dd.mm.yyyy |
5 | `DESCRIPTION` | | | BOLD |
6 |  |  |  |  show nothing | 
7 | `PUBLISHER` | none | | in the future it should be clickable and lead to a publisher entity page, currently simple text | 
8 | | none | המכרז בוטל | |
9(a-c)| | | | show nothing | 
10 | `SUBJECTS` | | label per each value. Each label should be linked to a search results page of procurement_tenders from the same topic | 
11a | `tender_id`| מספר מנו"ף | `tender_id` | |
11b | `tender_type` | סוג המכרז: | if `tender_type` == `office` -->  `משרדי` | |
11c | `` | מועד סגירה: ... בשעה... | | dd.mm.yyyy + HH:MM: | 
11d| `CONTACT` | אנשי קשר: | | email adresses should be clickable and open user's email clien
12 | | | | show nothing |
13 (a-d) | | | | show nothing |
14 | (table intro) | table shows a chronological history of the tender, in a reversed order. In this scenario we are focused only of tender status change (bolded), or uploaded/updated files (normal text for the entrie row) | |
14a | | | | show nothing | 
14b | (update date -- @akariv please add the right data source to implement | | if date == Today -->  `היום`, if Today - date <= 7 --> `ימים x לפני`, if Today- date < 4 weeks, divide days number by 7 -->  `לפני כ-x שבועות`, otherwise: raw date (DD.MM.YYYY) | |
14c | `quarterly_contract_spending_reports.REPORT-URL`| don't show address, just display the icon with a relevant link | | to be opened in a new tab|
14d | update message | | |needs to set logic to be handled in a separate issue, to be hanled in #52 | 
15 | grid intro, based on `procurement_tenders.DOCUMENTS` | `קבצים מצורפים` | | |
15a | `update_time` | none | (update date -- from either `quarterly_contract_spending_reports` or `procurement_tenders`) if date == Today -->  `היום`, if Today - date <= 7 --> `ימים x לפני`, if Today- date < 4 weeks, divide days number by 7 -->  `לפני כ-x שבועות`, otherwise: raw date (DD.MM.YYYY) ||
15b | icon + file name |  | icon to be set by the file type extention (doc/pdf/xls/csv), each element should be linked to the `link` address. If the number of elements is bigger than 3, start a new row of elements |

**Comment by noamoss** [comment]
@akariv please notice my question regarding 14b, and update the cell with the correct data source definition. Besides of that, seems like it can be assigned for development alongside #47

**Comment by akariv** [comment]
@noamoss - is this about getting the correct cancellation date? Is it published anywhere?

**Comment by noamoss** [comment]
@akariv nope, basically it is about showing a different status of the tender - בוטל - it is one of the values available in the `decision` field for office tenders (see [the summary table](https://docs.google.com/spreadsheets/d/1kF1rGO8_2Siri6UfgmawGBnA5Yu86QOz-P9iguqQNKM/edit?usp=drive_web&ouid=118432116584401393844), 1st tab).

**Comment by noamoss** [comment]
@akariv I assumed we have timestamp for the each file under the `documents` field: each file has a  key named 'update_time'.

**Comment by akariv** [comment]
Ah, ok - nevermind then :)

**Comment by akariv** [comment]
http://next.obudget.org/i/tenders/office/606016/15-2017

**Comment by noamoss** [comment]
@akariv looks good, should we close?
