### ISSUE TITLE
Quarterly report calculate exectued per transaction

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#59]
currently, we have the aggregated executed amount of payments per order_id + manof_ref.

We need to know per row the exact amount that has been transferred (paid). We can do so by subtracting the current executed amount from the previous (last transaction/reported row) executed.

**Comment by akariv** [comment]
Is this still relevant?

**Comment by noamoss** [comment]
@akariv it is, see #67 description
