### ISSUE TITLE
Create a Central Tenders/RFI/Group Agreement Page for open (new/updated) tenders

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#61]
(Invisoin link: https://projects.invisionapp.com/d/main#/console/7587193/276178413/preview )

![image](https://user-images.githubusercontent.com/3581741/36676957-a6d6cbc4-1b15-11e8-992e-fc752b2b9123.png)

Open Office Tender (`WHERE tender_type = 'central' AND decision='בתוקף'`)

dynamic values:
-------------

|No. | data source | label | value / logic | comments |
|---|---|---|---|---|
1 | any of the fields |none| if a value changed during  `TODAY <= LAST_UPDATE_DATE + 7 days`value should be `עודכן!`, if `TODAY <= START_DATE + 7 ` value should be `חדש!` |  do not use the `decision` field value here, as it is not reflecting what we intend to show with this label. | Don't use the raw value of the `decision` field, as it does not consist the required logic! |
2 | `decision` | none | `מכרז פתוח`: based on the  `decision` field: if `decision` == `בתוקף` ||
3 | `LAST_UPDATE_DATE` | `עדכון אחרון` | date | dd.mm.yyyy |
4 | `START_DATE` | `פרסום ראשון` | date | dd.mm.yyyy |
5 | `page_title` (transformed) | | take out the 'מכרז XXXX:', we should transform other types of tenders titles (RFI or Group Agreements) | BOLD |
6 | `decision` | none |  based on the  `decision` בםמאקמא || 
7 | | none | | `מנהל הרכש הממשלתי` | | 
8 | `quarterly_contract_spending_reports.supplier_name` | none | A. if the `tender_id` appears in `quarterly_contract_spending_reports.manof_ref` and `count('supplier_name') == 1`, display `supplier_name`). B. if `count('supplier_name') > 2, display `[num] ספקים`.  C. Otherwise, leave empty | 
9a | `quarterly_contract_spending_reports.executed`, `quarterly_contract_spending_reports.volume`| | pie chart || 
9b | `quarterly_contract_spending_reports.executed`, `quarterly_contract_spending_reports.volume` | 'עד כה בוצעו...% מתוך:` | `exectued` / `volume` | dd% (round result). Notice this formula should relate to ALL relevant suppliers (using `manof_ref`) |
9c | `quarterly_contract_spending_reports.executed` | none | sum of all `exectued` values for the relevant `manof_ref` | add NIS symbol to value|
10 | `SUBJECTS` | | label per each value. Each label should be linked to a search results page of procurement_tenders from the same topic | 
11 | 'description' | תיאור | | |
12a | `tender_id`| מספר מנו"ף | `tender_id` | |
12b | `REGULATION` | סוג: | if RFI --> `בקשת מידע`, if 'מכרז'--> מכרז מרכזי', if 'הסכם מסגרת' --> `הסכם מסגרת` | |
12c | `CLAIM_DATE` | מועד סגירה: ... בשעה... | | dd.mm.yyyy + HH:MM: | 
12d| `CONTACT` | אנשי קשר: | | email adresses should be clickable and open user's email client|
13a | actionable A # | | | to be handled on a follow #51 |
13b | actionable B # | | | to be handled on a follow #51 |
14 | (table intro) | table headers : `הזוכים במכרז`, ` סכום ההתקשרות`, `עד כה שולם` | values in this block are to be calculated by the intersection between current `tender_id` and `quarterly_contract_spending_reports.manof_ref`. Table should be sorted by the `value` amount (13b) in a decreasing order (biggest value, first row) | 
14a | `quarterly_contract_spending_reports.supplier_name` | | | in the future it would be linked to future entity page, currently nothing special | 
14b | `quarterly_contract_spending_reports.volume`| none, add a NIS symbol | sum of `quarterly_contract_spending_reports.volume` of the concrete supllier under the concrete `manof_ref` | don't round result, display real number (up to 2 digits after demical point)  | 
14c | `quarterly_c`quarterly_contract_spending_reports.executed`| none, add a NIS symbol | sum of `quarterly_contract_spending_reports.executed` of the concrete supllier under the concrete `manof_ref` | don't round result, display real number (up to 2 digits after demical point) | 
14d | | link to the relevant התקשרות page| | 
15 | (table intro) | table shows chronological history of the tender, in a reversed order. Two type of updates to be included: tender status change (bolded), payment (taken from the quarterly report) (bolded row), uploading/updating file (normal text for the entrie row) | |
15a |`quarterly_c`quarterly_contract_spending_reports.volume`, `quarterly_c`quarterly_contract_spending_reports.executed` | no headers | pie chart of the `executed` out of the total `volume` | the pie chart refers to the tender's total exectued out of the total approved values, not to be confused with 13 above  | 
15b | (update date -- from either  `quarterly_c`quarterly_contract_spending_reports` or `procurement_tenders` | | if date == Today -->  `היום`, if Today - date <= 7 --> `ימים x לפני`, if Today- date < 4 weeks, divide days number by 7 -->  `לפני כ-x שבועות`, otherwise: raw date (DD.MM.YYYY) | |
15c | `quarterly_contract_spending_report.PAGE_URL` or `quarterly_contract_spending_reports.REPORT-URL`| don't show address, just display the icon with a relevant link | | to be opened in a new tab|
15d | update message | | |needs to set logic to be handled in a separate issue, to be hanled in #52 | 
16 | grid intro, based on `procurement_tenders.DOCUMENTS` | `הוראות שעה וקבצים מצורפים` | | |
16a | `update_time` | none | (update date -- from either `quarterly_contract_spending_reports` or `procurement_tenders`) if date == Today -->  `היום`, if Today - date <= 7 --> `ימים x לפני`, if Today- date < 4 weeks, divide days number by 7 -->  `לפני כ-x שבועות`, otherwise: raw date (DD.MM.YYYY) ||
16b | icon + file name |  | icon to be set by the file type extention (doc/pdf/xls/csv), each element should be linked to the `link` address. If the number of elements is bigger than 3, start a new row of elements |

**Comment by noamoss** [comment]
main differences from the office tenders: items 5, 6, 7, 11, 12

**Comment by akariv** [comment]
@noamoss released from hold?

**Comment by noamoss** [comment]
@akariv I think you already tackled it through another issue, did not you? Anyhow, it is not on hold anymore,
