### ISSUE TITLE
contract-spending items should only link to existing / valid contract-spending items

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-app-generic-item#64]
## reproduction
* open this [contract-spending item link](http://next.obudget.org/i/contract-spending/%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%90%D7%95%D7%A6%D7%A8/4501313822/0083050502?li=24&theme=govbuy)
* click on another item from the table, e.g. the first item from 2015-01-12 - [שעות ייעוץ](https://next.obudget.org/i/contract-spending/4501004577/0098200130?theme=govbuy)

### expected
* show the item

### actual
* not found
![image](https://user-images.githubusercontent.com/1198854/38302214-8d3d5a68-380a-11e8-83c8-bf4ba85085cc.png)

**Comment by akariv** [comment]
I think that Mary already has an issue for that... need to add the
publisher_name to the link in questions.json

**Comment by OriHoch** [comment]
right
OpenBudget/BudgetKey#44
