### ISSUE TITLE
Translate Purchasing Methods into labels 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#68]
The purpose of this issue is to translate different purchasing methods into 1-3 words labels + more info  to show more (accessible) info of the original raw value, as part of #67 

see details at the 2nd tab of: https://docs.google.com/spreadsheets/d/1kF1rGO8_2Siri6UfgmawGBnA5Yu86QOz-P9iguqQNKM/edit#gid=1232287862 (second tab)

new version:

https://docs.google.com/spreadsheets/d/1JkZooBwoxKPlrXWWwUtNHLMdxc-iG0n5tdGZ23I8fYY/edit?ts=5b28da0a#gid=1250185114

**Comment by noamoss** [comment]
added link to the new spreadsheet.

**Comment by noamoss** [comment]
I am still suspecting it is oversimplified, but let's see when applied.

**Comment by akariv** [comment]
Let's use the tooltips mechanism to implement this @noamoss

**Comment by noamoss** [comment]
@akariv 

>Let's use the tooltips mechanism to implement this 

not sure I understand your intention - tooltips are about clarifying the literal meaning of a term/label, but in this issue (and in the design and the table mentioned above) we are offering an extra level of interpretation for the item's properties (combination).  Let's discuss.

**Comment by akariv** [comment]
This is not about the item property combinations.

This issue was about clarifying purchase methods (e.g. "תכ"ם 7.12.1"). I propose we do that using tooltips on all such cryptic terms so that hovering on the original text would reveal the easy to understand explanation.
