### ISSUE TITLE
Create a Purchasing Contact Page Queries (in process) 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#69]
This issue to include queries definitions for:

- התקשרות 
- מכרז
- פטור

**Comment by noamoss** [comment]
remember to include (כל המכרזים של הגורם המזמין / ספק)

**Comment by noamoss** [comment]
<div dir="rtl">

<b> התקשרות</b>

|שאילתה|פרמטרים משתנים| טורים בטבלת תוצאות
|---|----|--|
|כל ההתקשרויות המתועדות של הספק בשנים X | שנים| שם הספק, כותרת התקשרות, הגורם המזמין, סוג הרכש, סוג ההתקשרות, סטטוס התקשרות, סכום שאושר, סכום ששולם, תאריך פרסום, תאריך עדכון|
|כל ההתקשרויות המתועדות של הגורם המזמין X | שנים| הגורם המזמין, כותרת התקשרות, שם הספק,  סוג הרכש, סוג ההתקשרות, סטטוס התקשרות, סכום שאושר, סכום ששולם, תאריך פרסום, תאריך עדכון|
|כל ההתקשרויות ה[סטטוס] במסגרת הסעיף התקציבי | סטטוס התקשרות| שם הספק, כותרת התקשרות, הגורם המזמין, סוג הרכש, סוג ההתקשרות, סטטוס התקשרות, סכום שאושר, סכום ששולם, תאריך פרסום, תאריך עדכון
|כל ההתקשרויות הספק במסגרת רכש מסוג [סוג רכש]| [כל סוגי הרכש/מכרזים/מכרז מרכזי/מכרז משרדי/פטור ממכרז]| שם הספק, כותרת התקשרות, הגורם המזמין, סוג הרכש, סוג ההתקשרות, סטטוס התקשרות, סכום שאושר, סכום ששולם, תאריך פרסום, תאריך עדכון
|כל ההתקשרויות הגורם המפרסם במסגרת רכש מסוג [סוג רכש]| [כל סוגי הרכש/מכרזים/מכרז מרכזי/מכרז משרדי/פטור ממכרז]| הגורם המזמין, כותרת התקשרות, שם הספק, סוג הרכש, סוג ההתקשרות, סטטוס התקשרות, סכום שאושר, סכום ששולם, תאריך פרסום, תאריך עדכון
|כל ההתקשרויות הגורם המזמין בין הסכומים [מינימום] ו-[מקסימום] ש[אושרו/שולמו] | מינימום, מקסימום, אושרו/שולמו| הגורם המזמין, כותרת התקשרות, שם הספק, סוג הרכש, סוג ההתקשרות, סטטוס התקשרות, סכום שאושר, סכום ששולם, תאריך פרסום, תאריך עדכון


<b> מכרז מרכזי</b>

| שאילתה | פרמטרים משתנים | טורים בטבלת תוצאות |
|---|----|----|
כל ההתקשרויות המתועדות במסגרת המכרז | | הגורם המזמין, כותרת התקשרות, שם הספק, סוג ההתקשרות, סטטוס התקשרות, סכום שאושר, סכום ששולם, תאריך פרסום, תאריך עדכון
| כל פעולות הרכש המתועדות בהשתתפות הספק בשנים X | שנים | שם הספק, כותרת, שם הגורם המזמין, סוג פעולת הרכש, סטטוס פעולת הרכש, תקנה/סיבת הפטור, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון |
| כל פעולות הרכש המתועדות של מנהל הרכש הממשלתי בשנים X | שנים | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, תקנה/סיבת הפטור, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון |
כל פעולות הרכש מסוג [מכרז/מכרז מרכזי/מכרז משרדי/פטור ממכרז/הכל] בסטטוס [סטטוסים] בהשתתפות הספק | סוג פעולת רכש, סטטוס פעולת רכש  | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, תקנה/סיבת הפטור, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון
| כל פעולות הרכש המתועדות בנושא [נושא] בהשתתפות הספק  | נושא | שם הספק, כותרת, שם הגורם המזמין, סוג פעולת הרכש, תקנה/סיבת הפטור, סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון |
| כל פעולות הרכש בנושא [נושא] המתועדות של מנהל הרכש הממשלתי  | נושא | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, תקנה/סיבת הפטור, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון
|כל פעולות הרכש של מנהל הרכש הממשלתי בין הסכומים [מינימום] ו-[מקסימום] ש[אושרו/שולמו] | מינימום, מקסימום | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, תקנה/סיבת הפטור, סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות, תאריך פרסום | תאריך עדכון|
|כל פעולות הרכש של בהן מעורב הספק בין הסכומים [מינימום] ו-[מקסימום] ש[אושרו/שולמו] (לכל הספקים)| מינימום, מקסימום | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, תקנה/סיבת הפטור, סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות, תאריך פרסום | תאריך עדכון|


<b> מכרז משרדי</b>

| שאילתה | פרמטרים משתנים | טורים בטבלת תוצאות |
|---|----|----|
כל ההתקשרויות של הגורם המזמין במסגרת המכרז |  | הגורם המזמין, כותרת התקשרות, שם הספק, סוג הרכש, סוג ההתקשרות, סטטוס התקשרות, סכום שאושר, סכום ששולם, תאריך פרסום, תאריך עדכון
| כל פעולות הרכש המתועדות בהשתתפות הספק בשנים X | שנים | שם הספק, כותרת, שם הגורם המזמין, סוג פעולת הרכש, תקנה/סיבת הפטור,סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון |
| כל פעולות הרכש המתועדות של הגורם המזמין בשנים X | שנים | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון |
כל פעולות הרכש מסוג [מכרז/מכרז מרכזי/מכרז משרדי/פטור ממכרז/הכל] בסטטוס [סטטוסים] בהשתתפות הספק | סוג פעולת רכש, סטטוס פעולת רכש  | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון
| כל פעולות הרכש המתועדות בנושא [נושא] בהשתתפות הספק  | נושא | שם הספק, כותרת, שם הגורם המזמין, סוג פעולת הרכש, סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון |
| כל פעולות הרכש בנושא [נושא] המתועדות של הגורם המזמין בשנים  | נושא | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון
| כל פעולות הרכש בנושא [נושא] המתועדות של הגורם המזמין בשנים  | נושא | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון
|כל פעולות הרכש של הגורם המזמין בין הסכומים [מינימום] ו-[מקסימום] ש[אושרו/שולמו] | מינימום, מקסימום | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות, תאריך פרסום | תאריך עדכון|
|כל פעולות הרכש של בהן מעורב הספק בין הסכומים [מינימום] ו-[מקסימום] ש[אושרו/שולמו] (לכל הספקים)| מינימום, מקסימום | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות, תאריך פרסום | תאריך עדכון|

## פטור ממכרז

|שאילתה|פרמטרים משתנים| טורים בטבלת תוצאות
|---|----|--|

כל ההתקשרויות של הגורם המזמין במסגרת פטור המכרז הנבחר |  | הגורם המזמין, כותרת התקשרות, שם הספק, סוג הרכש, סיבת הפטור, סוג ההתקשרות, סטטוס התקשרות, סכום שאושר, סכום ששולם, תאריך פרסום, תאריך עדכון
| כל פעולות הרכש המתועדות בהשתתפות הספק בשנים X | שנים | שם הספק, כותרת, שם הגורם המזמין, סוג פעולת הרכש, סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון |
| כל פעולות הרכש המתועדות של הגורם המזמין בשנים X | שנים | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון |
כל פעולות הרכש מסוג [מכרז/מכרז מרכזי/מכרז משרדי/פטור ממכרז/הכל] בסטטוס [סטטוסים] בהשתתפות הספק | סוג פעולת רכש, סטטוס פעולת רכש  | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון
| כל פעולות הרכש המתועדות בנושא [נושא] בהשתתפות הספק  | נושא | שם הספק, כותרת, שם הגורם המזמין, סוג פעולת הרכש, סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון |
| כל פעולות הרכש בנושא [נושא] המתועדות של הגורם המזמין בשנים  | נושא | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון
| כל פעולות הרכש בנושא [נושא] המתועדות של הגורם המזמין בשנים  | נושא | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת רכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות | תאריך פרסום | תאריך עדכון
|כל פעולות הרכש של הגורם המזמין בין הסכומים [מינימום] ו-[מקסימום] ש[אושרו/שולמו] | מינימום, מקסימום | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות, תאריך פרסום | תאריך עדכון|
|כל פעולות הרכש של בהן מעורב הספק בין הסכומים [מינימום] ו-[מקסימום] ש[אושרו/שולמו] (לכל הספקים)| מינימום, מקסימום | הגורם המזמין, כותרת, שם הספק, סוג פעולת הרכש, סטטוס פעולת הרכש, סכום שאושר, סכום ששולם, מספר התקשרויות מתועדות, תאריך פרסום | תאריך עדכון|

</div>

**Comment by noamoss** [comment]
@akariv I believe we could unify some of the rows into a single (longer) query but not sure if would be more/less usable. Let's discuss if you think we should do so.

**Comment by noamoss** [comment]
@akariv I think we can close this issue, can't we?

**Comment by akariv** [comment]
Done with contracts.

**Comment by noamoss** [comment]
@akariv the contract query appears but does not work on an organization page in the social map.

**Comment by akariv** [comment]
Wait - what?
> the contract query appears but does not work on an organization page in the social map
the contract query is intended for the contract page, not an organization page.

**Comment by noamoss** [comment]
you are very right, I got confused. forget it. feel free to close if you are implementing other pages queries in other issues.

**Comment by akariv** [comment]
Added 3 queries to the tender page, based on the above and what we discussed.
