### ISSUE TITLE
Create a search result page

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#70]
https://projects.invisionapp.com/d/main#/console/7587193/253951995/preview

![image](https://user-images.githubusercontent.com/3581741/41255660-edf84aac-6dcf-11e8-9dec-ede9667102cc.png)

1. optional filters: "הכל", "מכרזים","מכרזים משרדיים","מכרזים מרכזיים","פטור ממכרז","התקשרויות". notice: מכרזים  will incldue both מכרזים משרדיים and מכרזים מרכזיים

2. time filter. label: "מועד פרסום", options: שבוע אחרון, חודש אחרון, שנה אחרונה, הכל, טווח תאריכים לבחירתך.

3. cancel the time graph.

4-7: search results items sorting logic: 
* in the same weight, an item with the queried item as a subject label will be shown first
* in the same weight, open/active items will be shown before a closed
* in the same weight, different kinds will be weighted by their type (descending order): central --> office --> exemption --> procurement. 

4-6(a): type
4-6(b): description
4-6(c): publisher 
4-6(d): supplier(s). add +[number] if more than one.
4-6(e): 8(e): label: אופן הרכש:, value: accessilbe (long)  version of `purchase_method`, as implemented on #68.
4-6(f): (optional): approved amount, don't remember to add ILS and to omit the decimal fraction.
4-6(g): start date - [optional: end date]. if now end date, leave empty space after '-'

7 (not in the demo) התקשרות item:
7(a) התקשרות
7(b) `purpose`
7(c) `publisher`,`purchasing unit` (like in https://github.com/OpenBudget/budgetkey-app-generic-item/issues/67).
7(d) (optional), `supplier`(s) - add + [number] if more than one. show the supplier with the biggest approved/executed amount.
8(e): label: סיבת הפטור, value: accessible (long) version, as implemented on #68.
8(f): (optional): approved amount, don't forget to add ILS and to omit the decimal fraction.
8(g): start date - [optional: end date] (end date to be shown only if the status has changed to inactive, otherwise show "התקשרות פעילה")

**Comment by akariv** [comment]
How is (4) different from (7)?
4-6(e) (what is 8(e)) - where is the 'long description'? Is it already in #68? Are you still working on it?
'approved amount' - what do you mean by that?
7(d) - contracts have one supplier by definition, so unclear

**Comment by noamoss** [comment]
>How is (4) different from (7)?

4 talks about tender(s)/procurement, and 7 about התקשרות

> 4-6(e) (what is 8(e)) - where is the 'long description'? Is it already in #68? Are you still working on it?

As we spoke, here you should/could take the value from the associated exemption page. It is the same value - and no, #68 is not ready yet, still requires my work (and someone who knows about it).

>'approved amount' - what do you mean by that?
סכום שאושר


> 7(d) - contracts have one supplier by definition, so unclear

correct, forget it then - just the single supplier's name

**Comment by akariv** [comment]
In the attached image (4) is a contract, (5) is an exemption and (6) is a tender.

**Comment by akariv** [comment]
Also for 4-6(e) - `purchase_method` is defined for contracts, not tenders.

**Comment by akariv** [comment]
4-6(g) - can you please specify the label for each of the cases?

**Comment by noamoss** [comment]
@akariv 


>4-6(g) - can you please specify the label for each of the cases?

תקופת אישור הרכש
