### ISSUE TITLE
 Create a  Tender Exemption Page

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#72]
(Invisoin link: https://projects.invisionapp.com/d/main#/console/7587193/276178413/preview )

(`FROM procurement_tenders_exemptions_processed`)
-------------

![image](https://user-images.githubusercontent.com/3581741/41255228-835ddd52-6dce-11e8-93d5-5de6f0a462f4.png)

|No. | data source | label | value / logic | comments |
|---|---|---|---|---|
1 | `decision` | none | translatae decision by [the doc coumns c-->d](https://docs.google.com/spreadsheets/d/1kF1rGO8_2Siri6UfgmawGBnA5Yu86QOz-P9iguqQNKM/edit#gid=0)| this is the sorten version of the decision (2-3 words)| 
2| `decision`| none |translatae decision by [the doc coumns c-->e](https://docs.google.com/spreadsheets/d/1kF1rGO8_2Siri6UfgmawGBnA5Yu86QOz-P9iguqQNKM/edit#gid=0)| this is the sorten version of the decision (2-3 words) | |
3| `publication_id`,`quarterly_contract_spending_reports.supplier_name` | | A. if the `publication_id` appears in quarterly_contract_spending_reports and count('supplier_name') == 1, display supplier_name). B. if count('supplier_name') > 2, display[num] ספקים`. C. Otherwise, leave empty
3 | `decision`, `page_title`|`מצב נוכחי` | `page_title`+", "+`decision`(raw text) |
4 | `reason` | `סיבות בקשת הפטור` | |
5 | `ספק/ים` |  | |<no change with the rest of the properties, label only>| 
7 | | | not relevant |

**Comment by noamoss** [comment]
@akariv 
We are taking data from a different table, but most of the relevant fields name are identical - I included in the issue only lines with other differences.

**Comment by akariv** [comment]
(2) which field is used for the main title (before the tag)
(3) we have a supplier name in the exemption - why not use it?

(7) why not relevant?

**Comment by noamoss** [comment]
(2) `description`, might need to trim (+"...") after 24 characters, but then to show the full text somehow.
(3) this is what I asked you about with the fingerprints. If you can catch all relevant suppliers for a single exemption in this table, go ahead. If there are chances for other suppliers that are involved in a procurement which is a result of this exemptions and will not show in this table, I assume it would be better to retrieve them from the external data source. 
(7) my mistake. very relevant.
