### ISSUE TITLE
Tender Exemption/Office/Central: Trim top description + add full value in page 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#76]
![image](https://user-images.githubusercontent.com/3581741/41397050-99199cf0-6fbb-11e8-8a51-2d1596e6a21d.png)

If the `description` field length > 34 : 
1. Trim the top description after 34 characters (+'....')
2. add a new label ("תיאור") with the full value

**Comment by akariv** [comment]
so, we would have מצב נוכחי and תיאור with the same value?

**Comment by noamoss** [comment]
closing this issue, found it is more complicated due to differences between the pages. Will open separate issues.
