### ISSUE TITLE
Central Tender page: Fix the update badge label ("New"/"Updated"/"Closed"), don't display N/A

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#77]
![image](https://user-images.githubusercontent.com/3581741/41397452-eb274622-6fbc-11e8-84a5-4d81517205ea.png)
(taken on http://next.obudget.org/i/tenders/central/553418/technology-2-2014?li=15)

Anyhow, we can not show the 'N/A'

Might be relevant for exemptions and office tenders as well (could tell what's the trigger for this behaviour)

**Comment by akariv** [comment]
This is what happens when `decision` has a value that not in spec - but in
this case it seems like a bug.

**Comment by noamoss** [comment]
so just for a better UX, let's hide the label (or show empty string) when the `decision` is out of spec. I suspect we are going to find many problems like that ( not only because of the state of data but also because of the rush in which I am currently defining it)

**Comment by akariv** [comment]
I'll keep it as N/A for now so that we know there's a missing translation (otherwise we'll never know). I will change to `''` before launch.
