### ISSUE TITLE
Tender Exemption/Central Tender/Office Tender, Files library: fix date label and extend clickable area

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#78]
![image](https://user-images.githubusercontent.com/3581741/41397645-8d85a1de-6fbd-11e8-81ea-a86e2473320a.png)
(taken on: http://next.obudget.org/i/tenders/central/553418/technology-2-2014?li=15)

1. No date is shown. If for any reason this is because there is actually no value in the date field, we should change label into: "תאריך פרסום לא ידוע", but this should be a real edge case scenario, as usually we have the date.

2. Make both icons clickable as well.

**Comment by akariv** [comment]
It seems that in this case we don't have the date:
https://www.mr.gov.il/CentralTenders/technology/Pages/2-2014.aspx

**Comment by noamoss** [comment]
@akariv so label placeholder should be in Hebrew: "תאריך לא ידוע"
