### ISSUE TITLE
Central Tender page: chronological graph shows ONLY transactions, no other steps in the process 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#79]
Follow up of #71:

![image](https://user-images.githubusercontent.com/3581741/41397959-7acf68ee-6fbe-11e8-8561-d88f659a041b.png)

(taken from http://next.obudget.org/i/tenders/central/553418/technology-2-2014?li=15)

When was it opened? closed? documents updated?

might be relevant for tender exemptions and office tenders as well

**Comment by akariv** [comment]
Can you share a link to the original webpage where this data is presented?

**Comment by noamoss** [comment]
https://www.mr.gov.il/CentralTenders/technology/Pages/2-2014.aspx

**Comment by noamoss** [comment]
yes, please see the link (i.e. הוראות שעה בתוקף)

actually there other details in this original page that are not shown in the page we built (סלים).

We need to think of a way to deal with these kind of elements.

**Comment by akariv** [comment]
> When was it opened? closed? documents updated?

It doesn't say any of these.

How is הוראות שעה בתוקף relevant to a tender from 2014?

**Comment by akariv** [comment]
Aha

Found this, which seems to be the same thing:
https://www.mr.gov.il/ExemptionMessage/Pages/ExemptionMessage.aspx?pID=553418
