### ISSUE TITLE
Central Tender Page: fix publication_id in the details section

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#81]
![image](https://user-images.githubusercontent.com/3581741/41398155-1e8d3c86-6fbf-11e8-8765-01f64b21562b.png)

**Comment by akariv** [comment]
What should it be then?

**Comment by noamoss** [comment]
RTL

**Comment by noamoss** [comment]
Also, see #84 #83

**Comment by akariv** [comment]
Based on #83 this is irrelevant, right?

**Comment by noamoss** [comment]
what is relevant is to make sure we don't replicate the same weird LTR behavior. I guess you would prefer to close this issue, just keep it in mind when taking care of #83.
