### ISSUE TITLE
Central Tender Page: fix header+details section

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#82]
![image](https://user-images.githubusercontent.com/3581741/41398329-ab737bb0-6fbf-11e8-8d87-71af707c52df.png)

1. Replace the `description` field in the top with `page_title`. 

2. Add label (`תיאור:`) + `description` value in the details section, right after the `publication_id` line.

**Comment by akariv** [comment]
מקור:
https://www.mr.gov.il/CentralTenders/technology/Pages/2-2014.aspx

**Comment by noamoss** [comment]
closing this in favour of #84
