### ISSUE TITLE
Central Tenders header+description rearrange

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#84]
![image](https://user-images.githubusercontent.com/3581741/41407388-ef5343e8-6fd7-11e8-964c-c8afa139da24.png)

Header:
(1) `page_title`

(3) description paragraph:
sub-title: פרטי המכרז

| label | field | comment |
| - | - | - |
| סוג המכרז: | מרכזי, + `, regulation` |
| :מספר המכרז | `publication_id` |if empty or '0', show `tender_id`  |
| :תיאור | `description` | |
| סטטוס: | `page_title` | 
| אנשי קשר | contact |

**Comment by akariv** [comment]
סטטוס:	page_title	 ?

**Comment by noamoss** [comment]
@akariv yea, I know it is surprising, but from what I saw on my redash journeys, for central tenders it includes info about the tender's status. would you mind verifying me?
