### ISSUE TITLE
Central Tender search results: fix supplier when no supplier

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#90]
https://next.obudget.org/s/?q=%D7%A6%D7%99%D7%95%D7%93%20%D7%9E%D7%A9%D7%A8%D7%93%D7%99&range=last_decade&dd=all:

![image](https://user-images.githubusercontent.com/3581741/41506061-0c081e84-721f-11e8-88d1-2f4d5d2fd506.png)

when there is no supplier,  leave empty - currently, the (long) description is being displayed. 

this is probably a duplication of #87.

**Comment by akariv** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/docs-delete-by-query.html

**Comment by noamoss** [comment]
checked and approved on live
