### ISSUE TITLE
Add Actionables by scenario for center+office tenders

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#95]
follow up of #51

**Comment by noamoss** [comment]
@akariv 

tenders: https://docs.google.com/spreadsheets/d/1JkZooBwoxKPlrXWWwUtNHLMdxc-iG0n5tdGZ23I8fYY/edit#gid=1250185114
exemptions: https://docs.google.com/spreadsheets/d/1lM2Afiw2JMJzHMIvWt3XylWLy2PLmVGbqaR9laBXFNo/edit#gid=1604640775

**Comment by akariv** [comment]
http://next.obudget.org/i/tenders/office/617332/21/2018?li=0
