### ISSUE TITLE
open procure: exemptions page, add missing fields to the details section

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-app-generic-item#97]
missing fields, by order:

* סוג הליך הרכש: [פטור ממכרז]
* מספר הפרסום: 
* מצב נוכחי : (this is the future extended_status)
* סיבות בקשת הפטור:  (already exists in the screen)
* הסתמכות על תקנה ('regulation' field in the db)

govbuy link: http://next.obudget.org/i/tenders/exemptions/502040/none?li=0&theme=govbuy
minhal harechesh link: https://www.mr.gov.il/ExemptionMessage/Pages/ExemptionMessage.aspx?pID=502040

expected location:

![image](https://user-images.githubusercontent.com/3581741/43390630-46c75180-93f7-11e8-9a05-ba7feac6593e.png)

**Comment by noamoss** [comment]
@akariv reopenning, as the screen, does look/work well:

![image](https://user-images.githubusercontent.com/3581741/43461157-70349020-94db-11e8-9f5a-4bdc153c1a5f.png)

1. missing details in the header.
2. status label should not appear if empty. if not empty, value should be displayed. 

If this issue is due to the exemptions values issue (handled else where) please reclose.

**Comment by akariv** [comment]
Link?

**Comment by noamoss** [comment]
same as in the description: http://next.obudget.org/i/tenders/exemptions/502040/none?li=0&theme=govbuy
